In [1]:
import numpy as np

In [56]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [57]:
# How many negative numbers are there?

result = a[a < 0]
print(len(result))
print(result)

4
[-2 -1 -6 -7]


In [58]:
# How many positive numbers are there?

result = a[a > 0]
print(len(result))
print(result)

5
[ 4 10 12 23  3]


In [59]:
# How many even positive numbers are there?

result = a[(a > 0) & (a % 2 == 0)]
print(len(result))
print(result)

3
[ 4 10 12]


In [6]:
# If you were to add 3 to each data point, how many positive numbers would there be?

b = a + 3
result = b[b > 0]
print(len(result))
print(result)

10
[ 7 13 15 26  1  2  3  3  3  6]


In [7]:
# If you squared each number, what would the new mean and standard deviation be?

c = a**2
print('The mean is: ', c.mean())
print('The standard deviation is: ', c.std())



The mean is:  74.0
The standard deviation is:  144.0243035046516


In [8]:
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set. 
# See this link for more on centering.

centered = a - a.mean()
print(centered)


[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [9]:
# Calculate the z-score for each data point. 
z_score_of_a = (a - a.mean()) / a.std()
print(z_score_of_a)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [10]:
# Copy the setup and exercise directions from More Numpy Practice 
# into your numpy_exercises.py and add your solutions.


In [11]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
print(sum_of_a)

55


In [13]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)
print(min_of_a)

1


In [14]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(a)
print(max_of_a)

10


In [15]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = sum(a) / len(a)
print(mean_of_a)

5.5


In [16]:
# Exercise 5 - Make a variable named product_of_a to hold the product 
# of multiplying all the numbers in the above list together

product_of_a = 1
for i in a:
    product_of_a *= i
print(product_of_a)

3628800


In [17]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = []
for i in a:
    squares_of_a.append(i**2)
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [18]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = []
for i in a:
    if i %2 != 0:
        odds_in_a.append(i)
print(odds_in_a)

[1, 3, 5, 7, 9]


In [19]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = []
for i in a:
    if i %2 == 0:
        evens_in_a.append(i)
print(evens_in_a)

[2, 4, 6, 8, 10]


In [20]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of 
# squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [21]:
# # Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# # **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)
    

b = np.array(b)

sum_of_b = b.sum()
print(sum_of_b)

33


In [22]:
# # Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

min_of_b = b.min()
print(min_of_b)

3


In [23]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = b.max()
print(max_of_b)

8


In [24]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = b.mean()
print(mean_of_b)

5.5


In [25]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number
product_of_b = b.prod()
print(product_of_b)

20160


In [26]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = b**2
print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


In [27]:
# # Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

odds_in_b = b[b % 2 != 0]
print(odds_in_b)

[3 5 7]


In [28]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

evens_in_b = b[b % 2 == 0]
print(evens_in_b)

[4 6 8]


In [29]:
# Exercise 9 - print out the shape of the array b
print(b.shape)

(2, 3)


In [30]:
# Exercise 10 - transpose the array b.
np.transpose(b)


array([[3, 6],
       [4, 7],
       [5, 8]])

In [31]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [32]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [33]:
## Setup 3
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c = np.array(c)

In [34]:
# Exercise 1 - Find the min, max, sum, and product of c.

print('min of c is:', c.min())
print('max of c is:', c.max())
print('sum of c is:', c.sum())
print('product of c is:', c.prod())


min of c is: 1
max of c is: 9
sum of c is: 45
product of c is: 362880


In [35]:
# Exercise 2 - Determine the standard deviation of c.
print('The standard deviation of c is:', c.std())


The standard deviation of c is: 2.581988897471611


In [36]:
# Exercise 3 - Determine the variance of c.
print('The variance of c is: ', c.var())

The variance of c is:  6.666666666666667


In [37]:
# Exercise 4 - Print out the shape of the array c
print(c.shape)

(3, 3)


In [38]:
# Exercise 5 - Transpose c and print out transposed result.
print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [39]:
# Exercise 6 - Get the dot product of the array c with c. 
print(np.dot(c,c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [40]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
print((c * np.transpose(c)).sum())


261


In [41]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
print((c * np.transpose(c)).prod())


131681894400


In [42]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)

In [43]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [44]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [45]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(c)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [46]:
# Exercise 4 - Find all the negative numbers in d
print(d[d < 0])

[-90 -30 -45 -45]


In [47]:
# Exercise 5 - Find all the positive numbers in d
print(d[d>0])

[ 90  30  45 120 180  45 270  90  60  45  90 180]


In [48]:
# Exercise 6 - Return an array of only the unique numbers in d.
print(np.unique(d))

[-90 -45 -30   0  30  45  60  90 120 180 270]


In [49]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [50]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [60]:
# Exercise 9 - Transpose and then print out the shape of d.
print(np.transpose(d))
print(np.shape(d))

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]
(3, 6)


In [52]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])